"""Add prod

Revision ID: 357afc570cfe
Revises: 49f8a550a4d1
Create Date: 2026-03-14 10:10:26.887680

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '357afc570cfe'
down_revision: Union[str, Sequence[str], None] = '49f8a550a4d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Сначала заполняем все NULL значения
    op.execute("UPDATE users SET email = CONCAT('user', id, '@example.com') WHERE email IS NULL")
    # Теперь делаем NOT NULL
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
